#!/usr/bin/env bash
# One-liner bootstrap for qbt-flow:
#   curl -fsSL https://raw.githubusercontent.com/smit-p/qbt-flow/main/setup.sh | bash
set -euo pipefail

REPO="https://github.com/smit-p/qbt-flow.git"
INSTALL_DIR="${QBT_FLOW_DIR:-$HOME/qbt-flow}"

# ── Colors & helpers ─────────────────────────────────────────────────────────
BOLD='\033[1m'   DIM='\033[2m'
GREEN='\033[32m' CYAN='\033[36m' YELLOW='\033[33m' RED='\033[31m'
RESET='\033[0m'

# All reads use /dev/tty so the script works with  curl … | bash
ask()      { local v; read -rp "$(echo -e "  $1")" v </dev/tty; printf '%s' "$v"; }
ask_s()    { local v; read -rsp "$(echo -e "  $1")" v </dev/tty; echo >&2; printf '%s' "$v"; }
ask_d()    { local v d="$2"; v=$(ask "$1 ${DIM}[$d]${RESET}: "); printf '%s' "${v:-$d}"; }
confirm()  { local r; r=$(ask "$1 ${DIM}(Y/n)${RESET}: "); [[ "${r,,}" != "n" ]]; }
confirm_n(){ local r; r=$(ask "$1 ${DIM}(y/N)${RESET}: "); [[ "${r,,}" == "y" ]]; }
info()     { echo -e "  ${GREEN}→${RESET} $*"; }
warn()     { echo -e "  ${YELLOW}!${RESET} $*"; }
header()   { echo -e "\n  ${BOLD}${CYAN}[$1]${RESET} ${BOLD}$2${RESET}\n"; }
sep()      { echo -e "  ${DIM}──────────────────────────────────────────────────${RESET}"; }

# ── Banner ───────────────────────────────────────────────────────────────────
echo ""
echo -e "  ${BOLD}╔═══════════════════════════════════════╗${RESET}"
echo -e "  ${BOLD}║         qbt-flow  installer           ║${RESET}"
echo -e "  ${BOLD}╚═══════════════════════════════════════╝${RESET}"
echo ""

# ── Check Python ─────────────────────────────────────────────────────────────
if ! command -v python3 &>/dev/null; then
    echo -e "  ${RED}✗${RESET} python3 not found. Install Python 3.8+ and try again."
    exit 1
fi

# ── Clone or update ──────────────────────────────────────────────────────────
if [[ -d "$INSTALL_DIR/.git" ]]; then
    info "Updating existing install at ${BOLD}$INSTALL_DIR${RESET} ..."
    git -C "$INSTALL_DIR" pull --ff-only -q
else
    info "Cloning qbt-flow to ${BOLD}$INSTALL_DIR${RESET} ..."
    git clone -q "$REPO" "$INSTALL_DIR"
fi

cd "$INSTALL_DIR"

# ── Existing config? ────────────────────────────────────────────────────────
if [[ -f config.env ]]; then
    echo ""
    warn "config.env already exists."
    if ! confirm_n "Reconfigure?"; then
        if confirm "Install / update systemd service?"; then
            echo ""
            exec bash "$INSTALL_DIR/install.sh"
        fi
        info "Done — no changes made."
        exit 0
    fi
    cp config.env "config.env.bak.$(date +%s)"
    info "Backed up existing config to config.env.bak.*"
fi

# ══════════════════════════════════════════════════════════════════════════════
#  Interactive configuration wizard
# ══════════════════════════════════════════════════════════════════════════════
CONFIG=""
add() { CONFIG+="$1"$'\n'; }

add "# qbt-flow configuration"
add "# Generated by setup.sh on $(date +%Y-%m-%d)"
add "# Full reference: config.env.example"
add ""

# ── 1. Media Servers ─────────────────────────────────────────────────────────
header "1/4" "Media Servers"
echo -e "  Which media servers do you use?"
echo -e "    ${BOLD}1${RESET}) Plex"
echo -e "    ${BOLD}2${RESET}) Jellyfin"
echo -e "    ${BOLD}3${RESET}) Emby"
echo ""
servers=$(ask "Enter numbers, e.g. ${BOLD}1 2${RESET}: ")

has_server() { [[ "$servers" == *"$1"* ]]; }

if has_server 1; then
    echo ""
    add "# Plex"
    plex_url=$(ask_d "Plex URL" "http://localhost:32400")
    plex_tok=$(ask_s "Plex Token ${DIM}(hidden)${RESET}: ")
    while [[ -z "$plex_tok" ]]; do
        warn "Token cannot be empty."
        plex_tok=$(ask_s "Plex Token ${DIM}(hidden)${RESET}: ")
    done
    add "PLEX_URL=$plex_url"
    add "PLEX_TOKEN=$plex_tok"
    add ""
fi

if has_server 2; then
    echo ""
    add "# Jellyfin"
    jf_url=$(ask_d "Jellyfin URL" "http://localhost:8096")
    jf_tok=$(ask_s "Jellyfin API Key ${DIM}(hidden)${RESET}: ")
    while [[ -z "$jf_tok" ]]; do
        warn "API key cannot be empty."
        jf_tok=$(ask_s "Jellyfin API Key ${DIM}(hidden)${RESET}: ")
    done
    add "JELLYFIN_URL=$jf_url"
    add "JELLYFIN_TOKEN=$jf_tok"
    add ""
fi

if has_server 3; then
    echo ""
    add "# Emby"
    emby_url=$(ask_d "Emby URL" "http://localhost:8920")
    emby_tok=$(ask_s "Emby API Key ${DIM}(hidden)${RESET}: ")
    while [[ -z "$emby_tok" ]]; do
        warn "API key cannot be empty."
        emby_tok=$(ask_s "Emby API Key ${DIM}(hidden)${RESET}: ")
    done
    add "EMBY_URL=$emby_url"
    add "EMBY_TOKEN=$emby_tok"
    add ""
fi

if ! has_server 1 && ! has_server 2 && ! has_server 3; then
    echo ""
    warn "No media server selected — qbt-flow needs at least one."
    warn "You can add one later by editing config.env."
    add "# TODO: add a media server"
    add "#PLEX_URL=http://localhost:32400"
    add "#PLEX_TOKEN="
    add ""
fi

# ── 2. qBittorrent ──────────────────────────────────────────────────────────
header "2/4" "qBittorrent Instances"
qbt_instances=""
n=1
while true; do
    echo -e "  ${BOLD}Instance $n${RESET}"
    qbt_host=$(ask_d "  Host" "localhost")
    qbt_port=$(ask_d "  Port" "8080")
    qbt_user=$(ask_d "  Username" "admin")
    qbt_pass=$(ask_s "  Password ${DIM}(hidden)${RESET}: ")
    while [[ -z "$qbt_pass" ]]; do
        warn "  Password cannot be empty."
        qbt_pass=$(ask_s "  Password ${DIM}(hidden)${RESET}: ")
    done

    entry="${qbt_host}:${qbt_port}:${qbt_user}:${qbt_pass}"
    if confirm_n "  Uses HTTPS?"; then
        entry+=":https"
    fi

    [[ -n "$qbt_instances" ]] && qbt_instances+=","
    qbt_instances+="$entry"
    ((n++))
    echo ""
    confirm_n "Add another instance?" || break
    echo ""
done

add "# qBittorrent"
add "QBT_INSTANCES=$qbt_instances"
add ""

# ── 3. Bandwidth ────────────────────────────────────────────────────────────
header "3/4" "Bandwidth"
echo -e "  ${DIM}Supports suffixes: 1Gbps, 500Mbps, 100MB/s, etc.${RESET}"
echo ""
bw_dl=$(ask_d "Download speed" "1Gbps")
bw_ul=$(ask "Upload speed ${DIM}(blank = same as download)${RESET}: ")
min_dl=$(ask_d "Min qBittorrent download floor" "10MB/s")
min_ul=$(ask_d "Min qBittorrent upload floor" "5MB/s")

add "# Bandwidth"
add "TOTAL_BANDWIDTH=$bw_dl"
[[ -n "$bw_ul" ]] && add "TOTAL_UPLOAD=$bw_ul"
add "MIN_QBT_DL=$min_dl"
add "MIN_QBT_UL=$min_ul"
add ""

# ── 4. Advanced ──────────────────────────────────────────────────────────────
header "4/4" "Advanced Options"

if confirm_n "Configure racing window?"; then
    echo ""
    rc_start=$(ask_d "  Window start hour (0-23)" "0")
    rc_end=$(ask_d "  Window end hour (0-23)" "7")
    rc_port=$(ask_d "  Racing instance port" "8080")
    rc_dl=$(ask_d "  Non-racing download cap" "1MB/s")
    rc_ul=$(ask_d "  Non-racing upload cap" "1MB/s")
    add "# Racing window"
    add "RACING_WINDOW_ENABLED=true"
    add "RACING_WINDOW_START=$rc_start"
    add "RACING_WINDOW_END=$rc_end"
    add "RACING_INSTANCE_PORT=$rc_port"
    add "RACING_NON_RACING_DL_LIMIT=$rc_dl"
    add "RACING_NON_RACING_UL_LIMIT=$rc_ul"
    add ""
fi

# Sensible defaults
add "# Tuning — see config.env.example for all options"
add "POLL_INTERVAL=15"
add "STREAM_OVERHEAD_FACTOR=1.25"
add "RAMP_UP_STEPS=3"
add "UNREACHABLE_ACTION=keep"

# ── Write config.env ────────────────────────────────────────────────────────
sep
echo ""
printf '%s' "$CONFIG" > config.env
chmod 600 config.env
info "config.env written ${DIM}(permissions: 600)${RESET}"

# ── Install systemd service? ────────────────────────────────────────────────
echo ""
if confirm "Install systemd service now?"; then
    echo ""
    bash "$INSTALL_DIR/install.sh"
else
    echo ""
    info "Skipped service install. Run later with:"
    echo -e "    cd $INSTALL_DIR && ./install.sh"
fi

echo ""
echo -e "  ${BOLD}${GREEN}✓ Setup complete!${RESET}"
echo ""
echo -e "  Config:     ${BOLD}$INSTALL_DIR/config.env${RESET}"
echo -e "  Reference:  ${BOLD}$INSTALL_DIR/config.env.example${RESET}"
echo ""
